
development:
  adapter: postgresql
  encoding: unicode
  database: grifter_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: grifter_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: grifter_production
  pool: 5

